### ISSUE TITLE
callback not firing in Firefox under certain circumstances

### ISSUE THREAD

**Issue by rhodey** [yoshuawuyts/observe-resize#4]
I'm creating a kind of infinite horizontal scrolling component and I do this with something like...

```html
<div class="scroller">
  <div class="time">
    <div class="limboLeft">won't ever see me</div>
    <div class="render">content in view</div>
    <div class="limboRight">won't ever see me</div>
  </div>
</div>
```

```css
.scroller {
  width: 100%;
  overflow-x: scroll;
  overflow-y: hidden;
}
.scroller > .time {
  width: 100000px;
  display: flex;
}
.scroller > .time > .limboLeft {
  background-color: red;
}
.scroller > .time > .render {
  background-color: green;
}
.scroller > .time > .limboRight {
  background-color: yellow;
}
```

```javascript
...blah() blah() blah()
  request animation frame...
  check if scroll position changed...
  update width of two spacers so that `.render` is the only thing in view...  
...blah() blah() blah()
```

I wanted to use `observe-resize` so I imported the module and registered a callback passing a reference to the `.scroller` element. problem is the callback only gets fired once on page load and then never again in FireFox. I tested the code in Chrome and the callback was fired as expected. I then tried replacing `observe-resize` with a good old `window.addEventListener('resize', cb)` and that also worked as expected in FireFox, but I can't get `observe-resize` to work...

at first I thought it might be something to do with my massive static-width div, and it still might, but I don't get any resize callbacks when resizing the height of my window either and that confuses me. FireFox 57.0.1 on Ubuntu 16.04, also tested in a "Private Browsing" window to ignore browser plugins and all that.
